from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'Files'
LOGO_DIR = FILES_DIR / 'Logo'
WINDOW_ICON_PATH = LOGO_DIR/ 'TempLogo.jpg'

#print(WINDOW_ICON_PATH)

# Fonts
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 1
MINIMUM_WIDTH = 400

# Colors
# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'