from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'Files'
LOGO_DIR = FILES_DIR / 'Logo'
WINDOW_ICON_PATH = LOGO_DIR / 'TempLogo.jpg'


# Colors
PRIMARY_COLOR = '#b93e3e'
DARKER_PRIMARY_COLOR = '#742929'
DARKEST_PRIMARY_COLOR = '#391515'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500
